### ISSUE TITLE
Images don't always appear after entry.

### ISSUE THREAD

**Issue by JohnnyBoyKing** [giowck/symphytum#105]
I have just started using Symphytum for a theatrical props database. So far I am impressed with the ease of use and basic capabilities, however I recently noticed that when I select the Table view, not all the jpg images in the records are displayed. If I switch to form view, they still don't display correctly. 

If I re-enter table view, different images are missing and some of the missing ones are then displayed.

I only have around 100 records so far - so not much data at all.

I have tried deleting and re-adding some of the images, to no avail.

Could you help please - **My Version is 2.5 Build 10**

**Comment by joshirio** [comment]
Hi, I'm looking for steps to reproduce the issue.

First of all, which operating system are you on and which version (Windows, macOS or Linux)?
Then does this affect only JPEG images or also other formats?

What would be really helpful is a sample database (without sensitive data) which can be exported via the backup dialog (File->Backup), that has the issue.

Also, did you activate the image caching functionality in the "advance" section of the settings?

**Comment by JohnnyBoyKing** [comment]
Hi There,

Thanks for your prompt response.

Info as follows :

I am running on Windows 7 SP1.

I have only used JPEGS so I have not tried other formats.

I have enabled image caching.

I cannot easily provide a copy of the database as it is 178 MB and GitHub appears to only let me add files of under 25MB!
- if there is a way around that, please let me know.

The problem also appears to be a loading issue?  - as after several minutes the missing images appear on both the table and form views!

Regards,
John King

**Comment by joshirio** [comment]
I know it's asking a lot for a database copy, so that would be helpful but we can also work this out in other ways, if this is not possible. BTW a nice service to send files (encrypted) is Send by Firefox: https://send.firefox.com/

The issue could be caused by really big image files, so maybe you are using high resolution images? Because each time the view is updated the files have to be read from disk and cropped which can consume a lot of time, especially when using spinning disks (instead of SSD). For this purpose the caching option was created, which you did enable, but I also cannot exclude a bug in that code.

I'll try to reproduce this, if you can't provide a database copy, the following way:

1. Install windows 7 in a VM (to exclude any windows 7 incompatibility issues)
2. Try loading many JPEGs with caching activated
3. If not reproducible, then ask for a sample JPEG file used, and retry

**Comment by JohnnyBoyKing** [comment]
I think you might be right about the JPEG file size - they are all between 1Mb and 1.5Mb.
What size would you recommend - 250Kb maybe?   I guess I can either crop them down or reduce the camera resolution.  The performance needs to be faster as the database will eventually have thousands of entries.

**Comment by JohnnyBoyKing** [comment]
I have replaced all the images with 50Kb versions, and the problem has gone!  Scrolling response on the table view is now fine, with no missing images!  Database size has dropped from 178MBb to 12Mb!

Thanks for your help and support with this!
