### ISSUE TITLE
Saving Files/Images into database directory

### ISSUE THREAD

**Issue by silviulaurentiu** [giowck/symphytum#111]
First of all, congratulation for this wonderful tool!

1. Regarding the saving of images and files, I think it could be helpful if they would be saved on the database directory using their original names. If the used manually explore the database directory, to be easy for him to understand which files are stored in the database directory.

2. If the same file (comparing the name, size and last changed date) will be tried to be added again to database, a bring pop-up window to inform the uses that this file already exists in the database and there are few options for him:
   A. The names, sizes and last changed date are identical. The user will be asked for:
       - only link the address of already existing file from database directory to current cell
       - replace existing file from database directory with the new file
       - add the new file with different name and then link its address to current cell
   B. The file names are different but the sizes and last changed date are identical. The user will be asked for:
      - only link the already existing file address from database directory to current cell
      - replace existing file from database directory with the new file; the other cells from database, which are linked with the old file address (name), will be updated to new file address and name.
      - add the new file and its address to current cell

**Comment by joshirio** [comment]
I think this adds unwanted complexity to the file management, for example then the software has to check for usage count for each file in all collection each time a file is deleted because if it deletes a file that is used somewhere else it will introduce data inconsistencies.

There are reasons why file names are internally md5 hashes. First of all not all file systems support all characters in file names like for example windows doesn't allow colons ':' in file names and some file systems and cloud services have a character size limit of file names... Then there's the issue of character sets, is UTF-8 allowed or only ASCII and so on...

The user is not supposed to navigate the internal database and file storage path. Files are exported with their original file names when the users uses the appropriate actions in Symphytum.

Regarding the management of duplicates to reduce disk usage, that is a job for a modern file system that supports compression, I think it is out of scope for such a simple personal database app, because each new feature and use case will introduce bugs, so better keep is simple.

Thanks for the suggestion, I hope you understand.

**Comment by silviulaurentiu** [comment]
Many thanks for your responses :-). No problem
