### ISSUE TITLE
Export: format description not correct

### ISSUE THREAD

**Issue by buhtz** [giowck/symphytum#28]
Using `Version 2.1 Build 6`.

The "Format:" field in the the Export-dialog says: __Comma-separated values (CSV)__
This is not full correct. Symphytum offers semicolon separated values, too.
I would suggest to correct that to just __CSV__.

**Comment by giowck** [comment]
This is because some software like MS Office handle CSV file format (.csv file extension) differently depending on country. American English default CSV separator is comma, conversely German or other European languages and localization use semicolon...

**Comment by buhtz** [comment]
You are unpolite closing a report without waiting for openers answer. The problem is not solved because you missunderstood my report.

This is UI-related. IT is about the string "Comma-separated values (CSV)" in the Export-dialog.

**Comment by giowck** [comment]
OK, was too fast and did not read correctly, now I get your point, sorry.

My understanding is that CSV stands for comma separated values which as a group might include other delimiters too...

Including the expanded name is intended to make it easier for users that don't know what CSV stands for. So this is why I'm not going to change it nor keep this issue open.

I prefer it that way because comma delimiter is still selected as default choice, leaving the semicolon option only for edge cases.
