### ISSUE TITLE
ver 2.2 does not open in Mint 18.2 after installation, when reverting to 2.1 it works. Any suggestions?

### ISSUE THREAD

**Issue by brunomant** [giowck/symphytum#47]
ver 2.2 does not open in Mint 18.2 after installation, when reverting to 2.1 it works. Any suggestions?

**Comment by joshirio** [comment]
Hi, Mint is based on Ubuntu 16.04.

Latest version of Symphytum requires at least Ubuntu 17.04 because the shipped Qt library version is too old.

As a workaround, you can download the [AppImage of Symphytum](https://github.com/giowck/symphytum/releases/download/v2.2/Symphytum-x86_64.AppImage) which runs on any linux distro.

I'm looking to build a snap package too, but it's a bit complex.
