### ISSUE TITLE
[Enhancement] Allow user-supplied date to be optional field

### ISSUE THREAD

**Issue by lamorton** [giowck/symphytum#56]
Presently, I don't see a way to set a date as an optional field (I mean the free-form date, not the creation/modification date).  Seems like it should be doable.  I'm building a list of action items, and some of them do not have a 'due by' date when I create them.

**Comment by joshirio** [comment]
OK please help me understand this. It is possible to add date fields to the form other than creation/modification time. Or do you mean, a date field which is not formatted? If so, you could just use text fields, otherwise you have to use one of the available date formats to make it work (sorting, date reminers, etc...).

![bildschirmfoto_2018-03-22_14-18-27](https://user-images.githubusercontent.com/12795018/37772762-ede5c992-2ddb-11e8-8806-c6f246c6f5d9.png)

**Comment by lamorton** [comment]
Yes, a date field that can be left empty (optional).

**Comment by joshirio** [comment]
Yes that makes sense. The issue is that technically a date cannot be empty. What I can do is to add a a checkbox "initialize with current date and time on record creation" (or something similar), if then this is unchecked, the default date which is 2000-01-01 00:00 is used. When you see that date you know it was not set and you can ignore it. I know, not ideal, but that's the best I can do.

Would that be acceptable?

**Comment by lamorton** [comment]
I suppose that would work.  Can you elaborate on why the date field cannot be empty?

**Comment by joshirio** [comment]
QDateTime can be null, but QDateTimeEdit which we use to edit and display dates won't accept null dates.
https://forum.qt.io/topic/3068/solved-enhancing-qdateedit-to-allow-for-null-empty-dates/17
