### ISSUE TITLE
Is it possible to lock the design of the form?

### ISSUE THREAD

**Issue by brianlah87** [giowck/symphytum#62]
Is it possible to lock the form design? This isn't for security purposes, it's just to prevent non-technical users who share the database from accidentally moving stuff around.

**Comment by joshirio** [comment]
Not yet but a feature which is useful indeed. I'll see what I can do for the next version.

**Comment by brianlah87** [comment]
This project is super useful - I'll try to spend some free time and go through the source to see if I can help.

Thank you so much for your time working on this.

**Comment by damaxel** [comment]
Does it make sense to disable (or remove) the icons for form editing (top bar, and left click) in the lock mode too? Not only the form design should be locked.

**Comment by joshirio** [comment]
The "lock form layout" button is just intended to prevent unwanted field movements when editing the database, so I don't think it makes much sense to completely disable editing of the database, also because it is unlikely to hit a button by accident, whereas moving a filed by mistake was quite common when using drag and drop with images/files...

But if you have any use case as an example that would justify the added effort, we can discuss this further in a separate GitHub issue.
