### ISSUE TITLE
How many records are possible in combo box ?

### ISSUE THREAD

**Issue by SebastienThibaut** [giowck/symphytum#85]
Hi,

Sorry for my english if it is not really good.
First, i find your application really great.

I'm trying to create a form to manage a stamps collection. I would like to know how many records can I put in a combo box, because I've imported by a text file more than 700 values directly in the database and after that I can't open the combo box.

You will find here the database.
[data.zip](https://github.com/giowck/symphytum/files/2861033/data.zip)

On the other side, if I insert a value in the field usign Symphytum, I can use it.
I would like to insert a lot of values once in the value.

Can you help me about that ?

Thank you very much.

Sebastien.

**Comment by joshirio** [comment]
Hi, how did you enter the items? You said you imported by text file. Symphytum has no option to import data into a combo box field.

It is discouraged to edit the fields directly by opening the database through a sqlite browser like the software called [sqlitebrowser](https://sqlitebrowser.org/).

The attached db file contains data such as:
`items:Abu Dhabi,Abyssinie,Açores (Portugal),Aden,Afars et Issas : Territoire français des,Afghanistan,Afrique Centrale Britannique,Afrique du Sud,Afrique du Sud : Compagnie britannique de l',Afrique du Sud-Ouest,Afrique Equatoriale Française,Afrique Occidentale Espagnole,Afrique Occidentale Française,Afrique Orientale Allemande,Afrique Orientale Britannique,Afrique Orientale Italienne,Aitutaki (Cook : îles),Ajman,Aland : îles,Alaouites (...)`

The problem is that internally Symphytum uses the ":" and "," characters to separate items, so that by entering manually the data from above, there are multiple ":" that are not escaped and thus Symphytum fails to recognize the correct metadata. When editing fields through Symphytum (default use case) characters are automatically escaped.

If an entry contains ":" or "," the following is done automatically by Symphytum and SQLite:
**: becomes \colon
, becomes \comma**

Because your use case is a corner case, I think it does make sense to edit the field values through sqlitebrowser, but we do have to be very careful to avoid mistakes and it is not guaranteed to work properly.

For example your data should be like this:
`items:Abu Dhabi,Abyssinie,Açores (Portugal),Aden,Afars et Issas \colon Territoire français des,Afghanistan,Afrique Centrale Britannique,Afrique du Sud,Afrique du Sud \colon Compagnie britannique de l',Afrique du Sud-Ouest,Afrique Equatoriale Française,Afrique Occidentale Espagnole,Afrique Occidentale Française,Afrique Orientale Allemande,Afrique Orientale Britannique,Afrique Orientale Italienne,Aitutaki (Cook \colon îles),Ajman,Aland \colon îles,Alaouites,Albanie,Alexandrette / Hatay,Alexandrie,Algérie,Allemagne (fédérale),Allemagne (fédérale) \colon Berlin-Ouest,Allemagne (fédérale \colon postes privées),Allemagne du Nord \colon Confédération de l',Allemagne \colon Empire (Reich),Allemagne \colon Empire (Reich \colon postes privées),Allemagne \colon Occupations \colon zone française,Allemagne \colon Occupations \colon zone soviétique,Allemagne \colon Occupations \colon zones améric. brit. (bizone),Allemagne \colon Occupations \colon zones améric. brit. et sov.,Allemagne \colon Postes locales période d'occupation,Allemagne \colon République Démocratique - RDA [DDR],Allenstein,Alsace-Lorraine,Alwar,Ancachs,Andorre (poste espagnole),Andorre (poste française),Angola,Angra,Anguilla,Anjouan,Annam et Tonkin,Antarctique australien \colon Territoire,Antarctique britannique \colon Territoire,Antigua-et-Barbuda,Antilles Danoises,Antilles Espagnoles,Antilles Néerlandaises,Antioquia (Colombie),Apurimac,Arabie du Sud \colon Fédération de l',Arabie Saoudite,Arad,Arbe et Veglia,Arequipa,Argentine,Argentine (postes privées),Arménie,Aruba,Ascension,Aurigny [Alderney],Australie,Australie du Sud,Australie Occidentale,Autriche,Autriche-Hongrie,Ayacucho,Azerbaïdjan,Bade (Ancien Etat),Bade (zone française \colon Allemagne),Bahamas,Bahawalpur,Bahrein,Bamra,Banat-Bacska,Bangkok,Bangladesh,Baranya,Barbade,Barbuda,Barcelone,Barwani,Basoutoland,Bavière,Bechuanaland,Belgique,Belgique (occupation allemande),Belgique (postes privées),Belize,Benadir,Bengasi,Bénin,Bequia (Grenadines de Saint-Vincent),Bergedorf,Berlin (zone soviétique \colon Allemagne),Bermudes,Bhopal,Bhore,Bhoutan,Biafra,Biélorussie / Bélarus,Bijawar,Birmanie,Bluefield,Bogota (Colombie),Bohême et Moravie,Bolivar (Colombie),Bolivie,Bophuthatswana,Bornéo du Nord,Bosnie-Herzégovine (poste bosniaque),Bosnie-Herzégovine (poste croate),Bosnie-Herzégovine (poste serbe),Bosnie-Herzégovine (austro-hongroise),Botswana,Boyaca (Colombie),Brême,Brésil,Brunei,Brunswick,Buenos Aires,Bulgarie,Bulgarie du Sud,Bundi,Burkina Faso,Burundi,Bushire,Bussahir,Cabo,Cachemire,Caicos \colon îles,Caïmans \colon îles,Calino,Cambodge,Cameroun,Cameroun britannique,Campione d'Italia,Canada,Canouan (Grenadines de Saint-Vincent),Canton,Cap de Bonne-Espérance,Cap Juby,Cap-Vert,Carchi,Carélie,Carinthie,Carolines \colon îles,Carthagène (Colombie),Caso,Castellorizo (occupation française),Castellorizo (occupation italienne \colon Egée),Cauca,Cavalle,Cayes de Belize,Centrafricaine \colon République,Ceylan,Chala,Chamba,Charkhari,Chiclayo,Chili,Chine (République Populaire),Chine (République \colon Taïwan),Chine Centrale,Chine du Nord,Chine du Nord-Est,Chine du Nord-Ouest,Chine du Sud,Chine du Sud-Ouest,Chine Orientale,Chine \colon Empire / République,Chine \colon Empire (bureaux allemands),Chine \colon Empire (bureaux américains),Chine \colon Empire (bureaux anglais),Chine \colon Empire (bureaux français),Chine \colon Empire (bureaux italiens),Chine \colon Empire (bureaux japonais),Chine \colon Empire (bureaux russes),Chine \colon Empire (postes locales),Christmas \colon île (Australie),Chypre,Chypre turque,Cilicie,Ciskei,Cochin,Cochinchine,Cocos \colon îles (Australie),Colombie,Colombie Britannique,Colonies françaises,Colonies italiennes,Colonies portugaises d'Afrique,Comores,Congo,Congo belge,Congo Kinshasa \colon République démocratique du,Congo portugais,Coo,Cook \colon îles,Cordoba,Corée (royaume / empire),Corée du Nord,Corée du Sud,Corfou,Corrientes,Costa Rica,Côte d'Ivoire,Côte de l'Or,Côte du Niger,Côte française des Somalis,Crète,Crète (bureau anglais \colon Heraklion),Crète (bureau italien \colon La Canée),Crète (bureau russe \colon Rethymno),Crète (bureaux autrichiens),Crète (bureaux français),Crète (poste des Insurgés),Croatie,Cuba,Cucuta,Cundinamarca,Curaçao,Cuzco,Cyrénaïque,Dahomey,Dalmatie,Danemark,Dantzig,Datia,Debrecen,Dédéagh,Deux-Siciles / Naples,Dhar,Diego Suarez,Djibouti,Dominicaine \colon République,Dominique,Dubai,Egée \colon îles de la mer,Eglise \colon Etats de l',Egypte,Elobey \colon Annobon et Corisco,Emirats Arabes Unis,Entre-Rios,Epire,Epire du Nord / Albanie (occupation grecque),Equateur,Erythrée,Espagne,Espagne (postes privées),Estonie,Eswatini,Etats de la Trêve,Etats-Unis d'Amérique,Ethiopie,Eupen et Malmédy,Falkland \colon îles,Falkland \colon îles (Dépendances),Faridkot,Fernando Poo,Féroé \colon îles,Fezzan (-Ghadamès),Fidji \colon îles,Finlande,Fiume,France,Fujeira,Funafuti (Tuvalu \colon îles),Funchal,Gabon,Gambie,Garzon,Géorgie,Géorgie du Sud et îles Sandwich du Sud,Ghadamès,Ghana,Gibraltar,Gilbert \colon îles,Gilbert-et-Ellice \colon îles,Gouvernement Général,Grande-Comore,Grèce,Grenade,Grenadines de Grenade (Carriacou et Petite Martinique),Grenadines de Saint-Vincent,Groenland,Guadeloupe,Guam,Guanacaste,Guatemala,Guernesey,Guinée,Guinée Equatoriale,Guinée espagnole,Guinée française,Guinée portugaise,Guinée-Bissau,Guyana,Guyane française,Gwalior,Haïti,Hambourg,Hambourg / Allemagne du Nord \colon Confédération de l',Hanovre,Haut-Jaffa (Arabie du Sud) (Arabie du,Haut-Karabakh / Artsakh,Haut-Sénégal et Niger,Haute-Silésie,Haute-Volta,Hawaii,Hedjaz,Héligoland,Hoi-Hao,Holkar / Indore,Honda,Honduras,Honduras britannique,Hong-Kong,Hongrie,Horta,Huacho,Hyderabad,Icarie,Idar,Ifni,Inde,Inde portugaise,Inde \colon Etablissements français dans l',Indes britanniques,Indes néerlandaises,Indochine,Indonésie,Ingrie du Nord,Inhambane,Inini,Ioniennes (îles),Irak,Iran,Irian Barat,Irlande,Islande,Israël,Istrie (Littoral slovène),Italie,Italie (postes privées),Italienne \colon République sociale,Jaipur,Jamaïque,Japon,Jasdan,Jersey,Jérusalem,Jhind,Johore (Malaisie),Jordanie,Kampuchéa,Katanga,Kathiri - Seiyun / Hadramaout (Arabie du Sud),Kazakhstan,Kedah (Malaisie),Kelantan (Malaisie),Kenya,Kenya - Ouganda - Tanzanie (Afrique de l'Est),Khmère \colon République,Khor Fakkan (Sharjah),Kiautschou,Kionga,Kirghizistan,Kirghizistan (Kyrgyz Express Post),Kiribati \colon îles,Kishengarh,Kosovo,Kosovo (Nations Unies),Kouang-Tchéou,Koweit,Krajina \colon République serbe de,La Aguera,Labuan,Lagos,Laos,Las Bela,Lattaquié,Leeward \colon îles,Lemnos,Lero,Lesotho,Lettonie,Levant (bureaux allemands),Levant (bureaux anglais),Levant (bureaux autrichiens),Levant (bureaux français),Levant (bureaux italiens),Levant (bureaux polonais),Levant (bureaux roumains),Levant (bureaux russes),Liban,Liban \colon Grand (mandat français),Liberia,Libye,Liechtenstein,Lipso,Lituanie,Lituanie centrale,Lituanie du sud,Lombardo-Vénétie,Lourenço Marques,Lubeck,Luxembourg,Luxembourg (occupation allemande),Macao,Macédoine du Nord,Madagascar,Madère (Portugal),Mahra (Arabie du Sud) (Arabie du,Malacca (Malaisie),Malaisie,Malaisie (Etats Malais fédérés),Malaisie / Territoires fédéraux [Wilayah persekutuan],Malawi,Maldives,Mali,Malte,Man \colon île de,Manama (Ajman),Mandchourie,Manizales,Mariannes \colon îles,Marienwerder,Maroc,Maroc (bureaux allemands),Maroc (bureaux anglais),Maroc (bureaux espagnols),Maroc espagnol,Marshall \colon îles,Martinique,Mascate et Oman,Maurice \colon île,Mauritanie,Mayotte,Mayreau (Grenadines de Saint-Vincent),Mecklembourg-Poméranie (zone soviétique \colon Allemagne),Mecklembourg-Schwerin (Ancien Etat),Mecklembourg-Strelitz (Ancien Etat),Medellin (Colombie),Memel,Mexique,Micronésie \colon Etats Fédérés de,Modène,Mohéli,Moldavie,Moluques du Sud [vignettes],Monaco,Mong-Tzeu,Mongolie,Mont Athos,Monténégro,Montserrat,Moquegua,Morvi,Moustique (Grenadines de Saint-Vincent),Moyen-Congo,Moyen-Orient,Mozambique,Mozambique \colon Compagnie de,Myanmar,Mytilène,Nabha,Namibie,Nandgame,Nanumaga (Tuvalu \colon îles),Nanuméa (Tuvalu \colon îles),Natal,Nations Unies (Genève),Nations Unies (New York),Nations Unies (Vienne),Nauru \colon île,Nedjed,Negri Sembilan (Malaisie),Népal,Nevis,Nicaragua,Niger,Nigeria,Nigeria du Nord,Nigeria du Sud,Nisiro,Niuafo'ou (Tonga \colon îles),Niue \colon île,Niutao (Tuvalu \colon îles),Norfolk \colon île (Australie),Norvège,Nossi-Bé,Nouveau-Brunswick,Nouvelle-Calédonie,Nouvelle-Ecosse,Nouvelle-Galles du Sud,Nouvelle-Guinée allemande,Nouvelle-Guinée néerlandaise,Nouvelle-Guinée \colon Territoire de,Nouvelle-Zélande,Nouvelle-Zélande (postes privées),Nouvelles-Hébrides,Nowanuggur,Nui (Tuvalu \colon îles),Nukufetau (Tuvalu \colon îles),Nukulaelae (Tuvalu \colon îles),Nyassa,Nyassaland,Obock,Océan Indien \colon Territoire britannique de l',Océanie \colon Etablissements français de l',Oldenbourg,Oman,Oman \colon Etat d' [vignettes],Orange \colon Etat libre d',Orcha,Ordre de Malte,Ostland,Oubangui-Chari,Ouganda,Outre-Djouba,Ouzbékistan,Pahang (Malaisie),Paita,Pakhoi,Pakistan,Palau \colon îles,Palestine mandataire,Palestine / Bande de Gaza (occupation égyptienne),Palestine / Cisjordanie (occupation jordanienne) / Cisjordanie (occupation,Palestinienne \colon Autorité,Palm \colon île (Grenadines de Saint-Vincent),Panama,Panama - Zone du Canal,Papouasie,Papouasie-Nouvelle-Guinée,Paraguay,Parme,Pasco,Patiala,Patmo,Pays-Bas,Pays-Bas (postes privées),Pays-Bas,Pays-Bas caribéens - Bonaire,Pays-Bas caribéens - Saba,Pays-Bas caribéens - Saint-Eustache,Penang / Pulau Pinang (Malaisie),Penrhyn (Cook \colon îles),Perak (Malaisie),Perlis (Malaisie),Pérou,Philippines,Pisco,Piscopi,Pitcairn \colon îles,Piura,Pologne,Polynésie française,Ponta Delgada,Port-Lagos,Port-Saïd,Portugal,Pountch,Pridnestrovie \colon République moldave de,Prince Edouard \colon île du,Prusse,Puerto Rico,Puno,Qatar,Qu'aiti - Hadramaout (Arabie du Sud),Queensland,Quelimane,Rajpeepla,Rarotonga (Cook \colon îles),Ras al Khaima,Redonda,Réunion,Rhénanie-Palatinat (zone française \colon Allemagne),Rhodes,Rhodésie (Afrique du Sud \colon Compagnie britannique de l'),Rhodésie (du Sud),Rhodésie du Nord,Rhodésie et Nyassaland,Rio de Oro,Rio Muni,Rio-Hacha,Romagne,Ross \colon Terre de,Rouad \colon île,Roumanie,Roumélie Orientale,Royaume-Uni,Royaume-Uni (postes privées),Ruanda-Urundi,Russie,Russie (Armées),Russie (occupation allemande) [Postgebiet Ob. Ost],Rwanda,Ryu-Kyu \colon îles,Sabah (Malaisie),Sahara Espagnol,Sahara Occidental [vignettes],Saint-Christopher-et-Nevis (-Anguilla),Saint-Kitts,Saint-Marin,Saint-Martin [Sint Maarten],Saint-Pierre-et-Miquelon,Saint-Vincent-et-les Grenadines,Sainte-Hélène,Sainte-Lucie,Sainte-Marie de Madagascar,Salomon \colon îles,Salvador \colon El,Samoa \colon îles,Samos,Santander (Colombie),Sao Tomé-et-Principe,Sarawak (Malaisie),Sardaigne,Sarre,Saseno,Saxe (Ancien Etat),Saxe (zone soviétique \colon Allemagne),Saxe occidentale (zone soviétique \colon Allemagne),Saxe orientale (zone soviétique \colon Allemagne),Scarpanto,Schleswig (plébiscite),Schleswig-Holstein (Ancien Etat),Selangor (Malaisie),Sénégal,Sénégambie et Niger,Serbie,Serbie-et-Monténégro,Setchouen,Seychelles,Seychelles (îles extérieures),Shanghai,Sharjah,Siam,Sierra Leone,Silésie orientale,Simi,Singapour,Singkiang / Turkestan Oriental / Turkestan,Sirmoor,Slovaquie,Slovénie,Somalie,Somalie italienne,Somaliland britannique,Soruth (9),Soudan (986),Soudan du Sud,Soudan français,Sri Lanka,Stampalia,Stellaland,Sud-Kasai,Suède,Suisse,Sungei Ujong,Suriname,Swaziland,Syrie,Syrie (mandat français),Szeged,Tadjikistan,Tahiti,Tanganyika,Tanger,Tanzanie,Tasmanie,Tchad,Tchécoslovaquie,Tchèque \colon République,Tchong-King,Temesvar (Timisoara),Terre-Neuve,Terres Australes et Antarctiques Françaises,Tete,Thaïlande,Thrace,Thuringe (zone soviétique \colon Allemagne),Timor-Oriental,Tobago,Tobago Cays (Grenadines de Saint-Vincent),Togo,Tokelau \colon îles,Tolima (Colombie),Tonga \colon îles,Toscane,Tour et Taxis,Touva,Transjordanie,Transkei,Transsylvanie,Transvaal,Travancore,Travancore-Cochin,Trengganu (Malaisie),Trente et Trieste,Trentin,Trieste - Zone A (anglo-américaine),Trieste - Zone B (yougoslave),Trinité-et-Tobago,Tripolitaine,Tristan da Cunha,Tumaco,Tunisie,Turkménistan,Turks et Caicos \colon îles,Turquie,Tuvalu \colon îles,Ukraine,Ukraine (occupation allemande),Umm al Qiwain,Union des Républiques Socialistes Soviétiques (URSS),Union \colon île (Grenadines de Saint-Vincent),Uruguay,Vaitupu (Tuvalu \colon îles),Vanuatu,Vathy,Vatican,Venda,Vénétie Julienne,Venezuela,Victoria,Vierges britanniques \colon îles,Vietnam,Vietnam (empire),Vietnam (Vietcong),Vietnam du Nord,Vietnam du Sud,Wadhwan,Wallis-et-Futuna,Wurtemberg (Ancien Etat),Wurtemberg (zone française \colon Allemagne),Yca,Yémen,Yémen du Nord \colon République arabe du,Yémen du Nord \colon Royaume du,Yémen du Sud,Yougoslavie,Young \colon île (Grenadines de Saint-Vincent),Yunnan,Yunnanfou,Zaïre,Zambézie,Zambie,Zanzibar,Zimbabwe,Zoulouland;`

Which would look like this:
![items fixed](https://user-images.githubusercontent.com/12795018/52861556-2a0b7d80-3133-11e9-9d66-b2de3bc5b7e6.png)

There's no limit that I am aware of regarding max combo box items, only available RAM guess.

**Comment by SebastienThibaut** [comment]
Hi,

Thank you very much for your answer.
I understand what you say and i'm agree with that.
But in my case i'd like to do this because I have a lot of value to insert like you've sawn it.

I've inserted these values with sqlitebrowser.

I will try your solution and I'll come back here to say the results.

Once again thank you for your answer and you application. I think it can be a really good app in the future.

Best regards,

Sébastien.
