### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by ppasserini** [giowck/symphytum#98]
Hi,

Lines from 1566 to 1571 into  symphytum/widgets/mainwindow.cpp are not translated (or I was not able to find (!) into the .ts file).
It's just the pop-up after the 2nd start to ask about automatic updates check.

Thanks

**Comment by joshirio** [comment]
It's because the .ts file was not up to date with the latest sources. It is advisable to run `lupdate -noobsolete Symphytum.pro` as described in the [translation doc](https://github.com/giowck/symphytum/blob/master/doc/translation/README) to fetsch the latest strings from code before updating the translation files.

I just did that manually and the latest italian .ts file can be found in master:
https://github.com/giowck/symphytum/blob/master/stuff/translations/symphytum_it.ts

**Comment by ppasserini** [comment]
Thank you for your support. Attached the latest, updated version of Italian lang.
[symphytum_it_20190621.zip](https://github.com/giowck/symphytum/files/3315585/symphytum_it_20190621.zip)

**Comment by joshirio** [comment]
Thanks
